### ISSUE TITLE
where da octopus?

### ISSUE THREAD

**Issue by peter-fang3100** [christ-church-grammar-school/major-project-mentos-fruit#11]
you give me octopus recipes, but where is octopus?

**Comment by Yavonix** [comment]
To find Octopus you need Shazam for food. We are seafood not seefood. Shazam not our vision.

**Comment by Yavonix** [comment]
To find Octopus you need Shazam for food. We are seafood not seefood. Shazam not our vision.

**Comment by peter-fang3100** [comment]
how dare you assign my question to me

**Comment by Yavonix** [comment]
Is very important question

**Comment by peter-fang3100** [comment]
yea but i'm the one asking, meaning i'm the one who don't know the answer, so no point assigning me lol
also shazam is scam

**Comment by Yavonix** [comment]
Lmao all I merely did was assign you your own question.. for you to answer... Ez. Also why am I able to edit your comments?!?

**Comment by peter-fang3100** [comment]
wtf that's a scam 
discord scam me
i want my $0 back
i don't like doing my own question, i like doing nothing
assign me to do nothing pls :3

anw i have figured out the answer to my question. you cannot find octopus because octopus is a lie.

**Comment by peter-fang3100** [comment]
it has been closed
